---
efiBootLoader: "grub"
kernelSearchPath: "/boot"
kernelPattern: "^vmlinuz.*"
loaderEntries: [ "timeout 5" ]
kernelParams: [ "quiet" ]
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
efiBootloaderId: "RedNext"
# also write EFI/BOOT/BOOTX64.EFI so firmware without NVRAM entries still boots
installEFIFallback: true
