---
efi:
    mountPoint:      "/boot/efi"
    recommendedSize: 512MiB
    minimumSize:     32MiB
    label:           "EFI"
userSwapChoices: [ none, file ]
initialSwapChoice: none
initialPartitioningChoice: erase
drawNestedPartitions: false
alwaysShowPartitionLabels: true
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4", "btrfs" ]
enableLuksAutomatedPartitioning: false
essentialMounts: [ "live-*", "control", "ventoy" ]
lvm:
    enable: false
