---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
showDonateUrl:          false
requirements:
    requiredStorage:    20
    requiredRam:        2.0
    internetCheckUrl:   [ http://example.com, http://google.com ]
    check:   [ ram, power, root ]
    required: [ ram, root ]
qmlSearch: both
qmlFilename: rednext-welcome
